// Auto-generated by generate.py — do not edit

import type { ELEMENT_NAMES, REQUIRED_ATTRIBUTES } from './constants.generated'

export type AvailableElement = (typeof ELEMENT_NAMES)[number]

export type AttributesAccessControl = {}

export type AttributesAccessPoint = {
	clock?: string
	desc?: string
	kdc?: string
	name: string
	router?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesAddress = {}

export type AttributesAllocationRole = {
	desc?: string
	name: string
	originUuid?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesAllocationRoleRef = {
	allocationRole?: string
	allocationRoleUuid?: string
	desc?: string
}

export type AttributesAnalogueWiringParameters = {
	desc?: string
	dsgInp?: string
	fctInp?: string
	id: string
	inpNam?: string
	inpRef?: string
}

export type AttributesAnalogueWiringParametersRef = {
	desc?: string
	id: string
}

export type AttributesApplication = {
	desc?: string
	name: string
	originUuid?: string
	templateUuid?: string
	type?: string
	uuid?: string
}

export type AttributesApplicationSclRef = {}

export type AttributesAssociation = {
	apRef: string
	associationID?: string
	desc?: string
	iedName: string
	initiator?: 'client' | 'server' | (string & {})
	kind: 'pre-established' | 'predefined' | (string & {})
	ldInst: string
	lnClass:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
	lnInst: string
	lnUuid?: string
	prefix?: string
}

export type AttributesAuthentication = {
	certificate?: string
	none?: string
	password?: string
	strong?: string
	weak?: string
}

export type AttributesBDA = {
	bType:
		| 'BOOLEAN'
		| 'INT8'
		| 'INT16'
		| 'INT24'
		| 'INT32'
		| 'INT64'
		| 'INT128'
		| 'INT8U'
		| 'INT16U'
		| 'INT24U'
		| 'INT32U'
		| 'FLOAT32'
		| 'FLOAT64'
		| 'Enum'
		| 'Dbpos'
		| 'Tcmd'
		| 'Quality'
		| 'Timestamp'
		| 'VisString32'
		| 'VisString64'
		| 'VisString65'
		| 'VisString129'
		| 'VisString255'
		| 'Octet64'
		| 'Unicode255'
		| 'Struct'
		| 'EntryTime'
		| 'Check'
		| 'ObjRef'
		| 'Currency'
		| 'PhyComAddr'
		| 'TrgOps'
		| 'OptFlds'
		| 'SvOptFlds'
		| 'LogOptFlds'
		| 'EntryID'
		| 'Octet6'
		| 'Octet16'
		| (string & {})
	count?:
		| 'T'
		| 'Test'
		| 'Check'
		| 'SIUnit'
		| 'Oper'
		| 'SBO'
		| 'SBOw'
		| 'Cancel'
		| 'Addr'
		| 'PRIORITY'
		| 'VID'
		| 'APPID'
		| 'TransportInUse'
		| 'IPClassOfTraffic'
		| 'IPv6FlowLabel'
		| 'IPAddressLength'
		| 'IPAddress'
		| (string & {})
	desc?: string
	name:
		| 'T'
		| 'Test'
		| 'Check'
		| 'SIUnit'
		| 'Oper'
		| 'SBO'
		| 'SBOw'
		| 'Cancel'
		| 'Addr'
		| 'PRIORITY'
		| 'VID'
		| 'APPID'
		| 'TransportInUse'
		| 'IPClassOfTraffic'
		| 'IPv6FlowLabel'
		| 'IPAddressLength'
		| 'IPAddress'
		| (string & {})
	sAddr?: string
	type?: string
	valImport?: string
	valKind?: 'Spec' | 'Conf' | 'RO' | 'Set' | (string & {})
}

export type AttributesBay = {
	desc?: string
	name: string
	templateUuid?: string
	uuid?: string
}

export type AttributesBayType = {}

export type AttributesBehaviorDescription = {
	desc?: string
	fileReference?: string
	format?: 'IEC 61131' | 'Textual' | 'Graphic' | (string & {})
	isSimulation?: string
	isSpecification?: string
	name: string
	originUuid?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesBehaviorDescriptionRef = {
	behaviorDescription?: string
	behaviorDescriptionUuid?: string
	desc?: string
}

export type AttributesBehaviorReference = {
	behaviorReference?: string
	behaviorUuid?: string
	desc?: string
}

export type AttributesBinaryWiringParameters = {
	debTm?: string
	desc?: string
	fastOutput?: string
	id: string
	inpNam?: string
	inpRef?: string
	outNam?: string
	outOffDl?: string
	outOnDl?: string
	outRef?: string
	outTyp?: 'Normally open' | 'Normally closed' | 'Change over' | (string & {})
	vInOff?: string
	vInOn?: string
}

export type AttributesBinaryWiringParametersRef = {
	desc?: string
	id: string
}

export type AttributesBitRate = {
	multiplier?:
		| ''
		| 'm'
		| 'k'
		| 'M'
		| 'mu'
		| 'y'
		| 'z'
		| 'a'
		| 'f'
		| 'p'
		| 'n'
		| 'c'
		| 'd'
		| 'da'
		| 'h'
		| 'G'
		| 'T'
		| 'P'
		| 'E'
		| 'Z'
		| 'Y'
		| (string & {})
	unit?: 'b/s'
}

export type AttributesCheckoutID = {
	desc?: string
	engRight?: 'full' | 'fix' | 'dataflow' | (string & {})
	fileName?: string
	fileType: 'SED' | 'SCC' | 'ICD' | 'IID' | 'CID' | 'SSD' | 'SCD' | (string & {})
	fileUuid?: string
	headerId?: string
	revision: string
	version: string
	when?: string
}

export type AttributesClientLN = {
	apRef: string
	desc?: string
	iedName: string
	ldInst: string
	lnClass:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
	lnInst: string
	lnUuid?: string
	prefix?: string
}

export type AttributesClientServices = {
	acceptServerInitiatedAssociation?: string
	bufReport?: string
	goose?: string
	gsse?: string
	maxAttributes?: string
	maxGOOSE?: string
	maxReports?: string
	maxSMV?: string
	noIctBinding?: string
	rGOOSE?: string
	rSV?: string
	readLog?: string
	supportsLdName?: string
	sv?: string
	unbufReport?: string
}

export type AttributesCommProt = {
	ipv6?: string
}

export type AttributesCommunication = {
	desc?: string
}

export type AttributesCommunicationServiceSpecifications = {
	desc?: string
}

export type AttributesConductingEquipment = {
	desc?: string
	name: string
	templateUuid?: string
	type:
		| 'CBR'
		| 'DIS'
		| 'VTR'
		| 'CTR'
		| 'GEN'
		| 'CAP'
		| 'REA'
		| 'CON'
		| 'MOT'
		| 'EFN'
		| 'PSH'
		| 'BAT'
		| 'BSH'
		| 'CAB'
		| 'GIL'
		| 'LIN'
		| 'RES'
		| 'RRC'
		| 'SAR'
		| 'TCF'
		| 'TCR'
		| 'IFL'
		| 'FAN'
		| 'SCR'
		| 'SMC'
		| 'PMP'
		| (string & {})
	uuid?: string
	virtual?: string
}

export type AttributesConfDataSet = {
	max: string
	maxAttributes?: string
	modify?: string
}

export type AttributesConfLNs = {
	fixLnInst?: string
	fixPrefix?: string
}

export type AttributesConfLdName = {}

export type AttributesConfLogControl = {
	max: string
}

export type AttributesConfReportControl = {
	bufConf?: string
	bufMode?: 'unbuffered' | 'buffered' | 'both' | (string & {})
	max: string
	maxBuf?: string
}

export type AttributesConfSG = {
	resvTms?: string
}

export type AttributesConfSigRef = {
	max: string
}

export type AttributesConnectedAP = {
	apName: string
	apUuid?: string
	desc?: string
	iedName: string
	redProt?: 'none' | 'hsr' | 'prp' | 'rstp' | (string & {})
}

export type AttributesConnectivityNode = {
	desc?: string
	name: string
	pathName: string
	templateUuid?: string
	uuid?: string
}

export type AttributesControlRef = {
	controlled?: string
	controlledDoName?: string
	controlledLNodeUuid?: string
	desc?: string
	extCtrlAddr?: string
	extCtrlUuid?: string
	originUuid?: string
	output: string
	outputInst?: string
	pDO?: string
	pLN?: string
	resourceName?: string
	resourceUuid?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesControllingLNode = {
	desc?: string
	outputName: string
	pLN?: string
	resourceName?: string
	resourceUuid?: string
}

export type AttributesDA = {
	bType:
		| 'BOOLEAN'
		| 'INT8'
		| 'INT16'
		| 'INT24'
		| 'INT32'
		| 'INT64'
		| 'INT128'
		| 'INT8U'
		| 'INT16U'
		| 'INT24U'
		| 'INT32U'
		| 'FLOAT32'
		| 'FLOAT64'
		| 'Enum'
		| 'Dbpos'
		| 'Tcmd'
		| 'Quality'
		| 'Timestamp'
		| 'VisString32'
		| 'VisString64'
		| 'VisString65'
		| 'VisString129'
		| 'VisString255'
		| 'Octet64'
		| 'Unicode255'
		| 'Struct'
		| 'EntryTime'
		| 'Check'
		| 'ObjRef'
		| 'Currency'
		| 'PhyComAddr'
		| 'TrgOps'
		| 'OptFlds'
		| 'SvOptFlds'
		| 'LogOptFlds'
		| 'EntryID'
		| 'Octet6'
		| 'Octet16'
		| (string & {})
	count?:
		| 'T'
		| 'Test'
		| 'Check'
		| 'SIUnit'
		| 'Oper'
		| 'SBO'
		| 'SBOw'
		| 'Cancel'
		| 'Addr'
		| 'PRIORITY'
		| 'VID'
		| 'APPID'
		| 'TransportInUse'
		| 'IPClassOfTraffic'
		| 'IPv6FlowLabel'
		| 'IPAddressLength'
		| 'IPAddress'
		| (string & {})
	dchg?: string
	desc?: string
	dupd?: string
	fc:
		| 'ST'
		| 'MX'
		| 'CO'
		| 'SP'
		| 'SG'
		| 'SE'
		| 'SV'
		| 'CF'
		| 'DC'
		| 'EX'
		| 'SR'
		| 'BL'
		| 'OR'
		| (string & {})
	name:
		| 'T'
		| 'Test'
		| 'Check'
		| 'SIUnit'
		| 'Oper'
		| 'SBO'
		| 'SBOw'
		| 'Cancel'
		| 'Addr'
		| 'PRIORITY'
		| 'VID'
		| 'APPID'
		| 'TransportInUse'
		| 'IPClassOfTraffic'
		| 'IPv6FlowLabel'
		| 'IPAddressLength'
		| 'IPAddress'
		| (string & {})
	qchg?: string
	sAddr?: string
	type?: string
	valImport?: string
	valKind?: 'Spec' | 'Conf' | 'RO' | 'Set' | (string & {})
}

export type AttributesDAI = {
	desc?: string
	ix?: string
	name:
		| 'T'
		| 'Test'
		| 'Check'
		| 'SIUnit'
		| 'Oper'
		| 'SBO'
		| 'SBOw'
		| 'Cancel'
		| 'Addr'
		| 'PRIORITY'
		| 'VID'
		| 'APPID'
		| 'TransportInUse'
		| 'IPClassOfTraffic'
		| 'IPv6FlowLabel'
		| 'IPAddressLength'
		| 'IPAddress'
		| (string & {})
	sAddr?: string
	valImport?: string
	valKind?: 'Spec' | 'Conf' | 'RO' | 'Set' | (string & {})
}

export type AttributesDAS = {
	desc?: string
	ix?: string
	mappedDaName?: string
	mappedLnUuid?: string
	name:
		| 'T'
		| 'Test'
		| 'Check'
		| 'SIUnit'
		| 'Oper'
		| 'SBO'
		| 'SBOw'
		| 'Cancel'
		| 'Addr'
		| 'PRIORITY'
		| 'VID'
		| 'APPID'
		| 'TransportInUse'
		| 'IPClassOfTraffic'
		| 'IPv6FlowLabel'
		| 'IPAddressLength'
		| 'IPAddress'
		| (string & {})
	valImport?: string
	valKind?: 'Spec' | 'Conf' | 'RO' | 'Set' | (string & {})
}

export type AttributesDAType = {
	desc?: string
	id: string
	iedType?: string
}

export type AttributesDO = {
	accessControl?: string
	desc?: string
	name: string
	transient?: string
	type: string
}

export type AttributesDOI = {
	accessControl?: string
	desc?: string
	ix?: string
	name: string
}

export type AttributesDOS = {
	desc?: string
	mappedDoName?: string
	mappedLnUuid?: string
	name: string
}

export type AttributesDOType = {
	cdc:
		| 'SPS'
		| 'DPS'
		| 'INS'
		| 'ENS'
		| 'ACT'
		| 'ACD'
		| 'SEC'
		| 'BCR'
		| 'HST'
		| 'VSS'
		| 'MV'
		| 'CMV'
		| 'SAV'
		| 'WYE'
		| 'DEL'
		| 'SEQ'
		| 'HMV'
		| 'HWYE'
		| 'HDEL'
		| 'SPC'
		| 'DPC'
		| 'INC'
		| 'ENC'
		| 'BSC'
		| 'ISC'
		| 'APC'
		| 'BAC'
		| 'SPG'
		| 'ING'
		| 'ENG'
		| 'ORG'
		| 'TSG'
		| 'CUG'
		| 'VSG'
		| 'ASG'
		| 'CURVE'
		| 'CSG'
		| 'DPL'
		| 'LPL'
		| 'CSD'
		| 'CST'
		| 'BTS'
		| 'UTS'
		| 'LTS'
		| 'GTS'
		| 'MTS'
		| 'NTS'
		| 'STS'
		| 'CTS'
		| 'OTS'
		| 'VSD'
		| 'ORS'
		| 'TCS'
		| (string & {})
	desc?: string
	id: string
	iedType?: string
}

export type AttributesDataObjectDirectory = {}

export type AttributesDataSet = {
	desc?: string
	name: string
	templateUuid?: string
	uuid?: string
}

export type AttributesDataSetDirectory = {}

export type AttributesDataTypeTemplates = {}

export type AttributesDynAssociation = {
	max?: string
}

export type AttributesDynDataSet = {
	max: string
	maxAttributes?: string
}

export type AttributesEnumType = {
	desc?: string
	id: string
}

export type AttributesEnumVal = {
	desc?: string
	ord: string
}

export type AttributesEqFunction = {
	desc?: string
	name: string
	templateUuid?: string
	type?: string
	uuid?: string
}

export type AttributesEqSubFunction = {
	desc?: string
	name: string
	templateUuid?: string
	type?: string
	uuid?: string
}

export type AttributesExtCtrl = {
	apRef?: string
	checkInterlock?: 'true' | 'false' | 'conserve' | (string & {})
	checkSynchrocheck?: 'true' | 'false' | 'conserve' | (string & {})
	desc?: string
	doName?: string
	iedName?: string
	intAddr?: string
	ldInst?: string
	lnClass?:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
	lnInst?: string
	lnUuid?: string
	pDO?: string
	pLN?:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
	prefix?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesExtRef = {
	daName?: string
	desc?: string
	doName?: string
	iedName?: string
	intAddr?: string
	ldInst?: string
	lnClass?:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
	lnInst?: string
	lnUuid?: string
	pDA?: string
	pDO?: string
	pLN?:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
	pServT?: 'Poll' | 'Report' | 'GOOSE' | 'SMV' | (string & {})
	prefix?: string
	serviceType?: 'Poll' | 'Report' | 'GOOSE' | 'SMV' | (string & {})
	srcCBName?: string
	srcCBUuid?: string
	srcLDInst?: string
	srcLNClass?:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
	srcLNInst?: string
	srcPrefix?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesFCDA = {
	daName?: string
	doName?: string
	fc:
		| 'ST'
		| 'MX'
		| 'CO'
		| 'SP'
		| 'SG'
		| 'SE'
		| 'SV'
		| 'CF'
		| 'DC'
		| 'EX'
		| 'SR'
		| 'BL'
		| 'OR'
		| (string & {})
	ix?: string
	ldInst?: string
	lnClass?:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
	lnInst?: string
	lnUuid?: string
	prefix?: string
}

export type AttributesFileHandling = {
	ftp?: string
	ftps?: string
	mms?: string
}

export type AttributesFunction = {
	desc?: string
	name: string
	templateUuid?: string
	type?: string
	uuid?: string
}

export type AttributesFunctionCatRef = {
	function?: string
	functionUuid?: string
}

export type AttributesFunctionCategory = {
	desc?: string
	name: string
	originUuid?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesFunctionCategoryRef = {
	desc?: string
	functionCategory?: string
	functionCategoryUuid?: string
}

export type AttributesFunctionRef = {
	desc?: string
	function?: string
	functionUuid?: string
}

export type AttributesFunctionRole = {
	cardinality?: '0..1' | '1..1' | '0..n' | '1..n' | (string & {})
	desc?: string
	max?: string
	name: string
	originUuid?: string
	selector?: string
	templateUuid?: string
	type?: string
	uuid?: string
}

export type AttributesFunctionRoleContent = {
	roleInst?: string
}

export type AttributesFunctionSclRef = {}

export type AttributesFunctionTemplate = {
	desc?: string
	name: string
	originUuid?: string
	templateUuid?: string
	type?: string
	uuid?: string
}

export type AttributesFunctionalSubVariant = {
	desc?: string
	isBaseline?: string
	name: string
	originUuid?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesFunctionalVariant = {
	desc?: string
	isBaseline?: string
	name: string
	originUuid?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesFunctionalVariantGroup = {
	desc?: string
	name: string
	originUuid?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesFunctionalVariantRef = {
	functionalVariant?: string
	functionalVariantUuid?: string
	update?: 'add' | 'remove' | (string & {})
}

export type AttributesGOOSE = {
	fixedOffs?: string
	goose?: string
	max: string
	rGOOSE?: string
}

export type AttributesGOOSEMcSecurity = {
	encryption?: string
	signature?: string
}

export type AttributesGOOSESecurity = {
	desc?: string
	name: string
	serialNumber: string
	templateUuid?: string
	uuid?: string
	xferNumber?: string
}

export type AttributesGSE = {
	cbName: string
	cbUuid?: string
	desc?: string
	ldInst: string
}

export type AttributesGSEControl = {
	appID: string
	confRev?: string
	datSet?: string
	desc?: string
	fixedOffs?: string
	name: string
	securityEnable?: 'None' | 'Signature' | 'SignatureAndEncryption' | (string & {})
	templateUuid?: string
	type?: 'GSSE' | 'GOOSE' | (string & {})
	uuid?: string
}

export type AttributesGSEDir = {}

export type AttributesGSESettings = {
	appID?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
	cbName?: 'Conf' | 'Fix' | (string & {})
	datSet?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
	dataLabel?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
	kdaParticipant?: string
}

export type AttributesGSSE = {
	max: string
}

export type AttributesGeneralEquipment = {
	desc?: string
	name: string
	templateUuid?: string
	type: 'AXN' | 'BAT' | 'MOT' | 'FAN' | 'FIL' | 'PMP' | 'TNK' | 'VLV' | (string & {})
	uuid?: string
	virtual?: string
}

export type AttributesGetCBValues = {}

export type AttributesGetDataObjectDefinition = {}

export type AttributesGetDataSetValue = {}

export type AttributesGetDirectory = {}

export type AttributesGooseParameters = {
	cbName?: string
	desc?: string
	dsName?: string
	goId?: string
	id: string
	maxTime?: string
	minTime?: string
	securityEnabled?: string
}

export type AttributesGooseParametersRef = {
	desc?: string
	id: string
}

export type AttributesHeader = {
	baseUuid?: string
	fileType?: 'ICD' | 'IID' | 'CID' | 'SSD' | 'SCD' | 'SED' | (string & {})
	id: string
	nameStructure?: 'IEDName' | (string & {})
	revision?: string
	toolID?: string
	uuid: string
	version?: string
}

export type AttributesHistory = {}

export type AttributesHitem = {
	revision: string
	version: string
	what?: string
	when: string
	who?: string
	why?: string
}

export type AttributesIED = {
	configVersion?: string
	desc?: string
	engRight?: 'full' | 'fix' | 'dataflow' | (string & {})
	manufacturer?: string
	name: string
	originalSclRelease?: string
	originalSclRevision?: string
	originalSclVersion?: string
	owner?: string
	templateUuid?: string
	type?: string
	uuid?: string
}

export type AttributesIEDName = {
	apRef: string
	apUuid?: string
	ldInst?: string
	ldUuid?: string
	lnClass?:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
	lnInst?: string
	lnUuid?: string
	prefix?: string
}

export type AttributesIEDSourceFiles = {}

export type AttributesInputVar = {
	daName?: string
	dataName?: string
	desc?: string
	doName?: string
	inputName?: string
	inputUuid?: string
	lnodeUuid?: string
	value?: string
	varName: string
}

export type AttributesInputVarRef = {
	desc?: string
	value?: string
	variable?: string
}

export type AttributesInputs = {
	desc?: string
}

export type AttributesIssuerName = {
	commonName: string
	idHierarchy: string
}

export type AttributesKDC = {
	apName: string
	apUuid?: string
	iedName: string
}

export type AttributesL2CommParameters = {
	appId?: string
	desc?: string
	macAddr?: string
	vlanId?: string
	vlanPriority?: string
}

export type AttributesL3IPv4CommParameters = {
	IPv4?: string
	'IPv4-IGMPv3Src'?: string
	appId?: string
	desc?: string
	vlanId?: string
	vlanPriority?: string
}

export type AttributesL3IPv6CommParameters = {
	IPv6?: string
	'IPv6-IGMPv3Src'?: string
	appId?: string
	desc?: string
	vlanId?: string
	vlanPriority?: string
}

export type AttributesLDevice = {
	desc?: string
	inst: string
	ldName?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesLN = {
	desc?: string
	inst: string
	lnClass:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
	lnType: string
	prefix?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesLN0 = {
	desc?: string
	inst: string
	lnClass:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
	lnType: string
	templateUuid?: string
	uuid?: string
}

export type AttributesLNode = {
	desc?: string
	iedName?: string
	ldInst?: string
	lnClass:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
	lnInst?: string
	lnType?: string
	lnUuid?: string
	prefix?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesLNodeDataRef = {
	daName?: string
	data?: string
	desc?: string
	doName?: string
	lnodeUuid?: string
}

export type AttributesLNodeInputRef = {
	desc?: string
	sourceRef?: string
	sourceRefUuid?: string
}

export type AttributesLNodeInputs = {
	desc?: string
}

export type AttributesLNodeOutputRef = {
	controlRef?: string
	controlRefUuid?: string
	desc?: string
}

export type AttributesLNodeOutputs = {
	desc?: string
}

export type AttributesLNodeSpecNaming = {
	sIedName?: string
	sLdInst?: string
	sLnClass?:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
	sLnInst?: string
	sPrefix?: string
}

export type AttributesLNodeType = {
	desc?: string
	id: string
	iedType?: string
	lnClass:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
}

export type AttributesLabel = {
	id?: string
	lang: string
}

export type AttributesLabels = {
	desc?: string
}

export type AttributesLine = {
	desc?: string
	name: string
	nomFreq?: string
	numPhases?: string
	templateUuid?: string
	type?: string
	uuid?: string
}

export type AttributesLog = {
	desc?: string
	name?: string
}

export type AttributesLogControl = {
	bufTime?: string
	datSet?: string
	desc?: string
	intgPd?: string
	ldInst?: string
	lnClass?:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
	lnInst?: string
	logEna?: string
	logName: string
	name: string
	prefix?: string
	reasonCode?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesLogParameters = {
	cbName?: string
	desc?: string
	dsName?: string
	id: string
	intgPd?: string
	logEna?: string
	logLdInst?: string
	logLnClass?:
		| 'LLN0'
		| 'LPHD'
		| 'LCCH'
		| 'LGOS'
		| 'LSVS'
		| 'LTIM'
		| 'LTMS'
		| 'LTRK'
		| 'ANCR'
		| 'ARCO'
		| 'ARIS'
		| 'ATCC'
		| 'AVCO'
		| 'CALH'
		| 'CCGR'
		| 'CILO'
		| 'CPOW'
		| 'CSWI'
		| 'CSYN'
		| 'FCNT'
		| 'FCSD'
		| 'FFIL'
		| 'FLIM'
		| 'FPID'
		| 'FRMP'
		| 'FSPT'
		| 'FXOT'
		| 'FXUT'
		| 'GAPC'
		| 'GGIO'
		| 'GLOG'
		| 'GSAL'
		| 'IARC'
		| 'IHMI'
		| 'ISAF'
		| 'ITCI'
		| 'ITMI'
		| 'ITPC'
		| 'KFAN'
		| 'KFIL'
		| 'KPMP'
		| 'KTNK'
		| 'KVLV'
		| 'MDIF'
		| 'MENV'
		| 'MFLK'
		| 'MHAI'
		| 'MHAN'
		| 'MHYD'
		| 'MMDC'
		| 'MMET'
		| 'MMTN'
		| 'MMTR'
		| 'MMXN'
		| 'MMXU'
		| 'MSQI'
		| 'MSTA'
		| 'PDIF'
		| 'PDIR'
		| 'PDIS'
		| 'PDOP'
		| 'PDUP'
		| 'PFRC'
		| 'PHAR'
		| 'PHIZ'
		| 'PIOC'
		| 'PMRI'
		| 'PMSS'
		| 'POPF'
		| 'PPAM'
		| 'PRTR'
		| 'PSCH'
		| 'PSDE'
		| 'PTEF'
		| 'PTHF'
		| 'PTOC'
		| 'PTOF'
		| 'PTOV'
		| 'PTRC'
		| 'PTTR'
		| 'PTUC'
		| 'PTUF'
		| 'PTUV'
		| 'PUPF'
		| 'PVOC'
		| 'PVPH'
		| 'PZSU'
		| 'QFVR'
		| 'QITR'
		| 'QIUB'
		| 'QVTR'
		| 'QVUB'
		| 'QVVR'
		| 'RADR'
		| 'RBDR'
		| 'RBRF'
		| 'RDIR'
		| 'RDRE'
		| 'RDRS'
		| 'RFLO'
		| 'RMXU'
		| 'RPSB'
		| 'RREC'
		| 'RSYN'
		| 'SARC'
		| 'SCBR'
		| 'SIMG'
		| 'SIML'
		| 'SLTC'
		| 'SOPM'
		| 'SPDC'
		| 'SPTR'
		| 'SSWI'
		| 'STMP'
		| 'SVBR'
		| 'TANG'
		| 'TAXD'
		| 'TCTR'
		| 'TDST'
		| 'TFLW'
		| 'TFRQ'
		| 'TGSN'
		| 'THUM'
		| 'TLVL'
		| 'TMGF'
		| 'TMVM'
		| 'TPOS'
		| 'TPRS'
		| 'TRTN'
		| 'TSND'
		| 'TTMP'
		| 'TTNS'
		| 'TVBR'
		| 'TVTR'
		| 'TWPH'
		| 'XCBR'
		| 'XSWI'
		| 'YEFN'
		| 'YLTC'
		| 'YPSH'
		| 'YPTR'
		| 'ZAXN'
		| 'ZBAT'
		| 'ZBSH'
		| 'ZCAB'
		| 'ZCAP'
		| 'ZCON'
		| 'ZGEN'
		| 'ZGIL'
		| 'ZLIN'
		| 'ZMOT'
		| 'ZREA'
		| 'ZRES'
		| 'ZRRC'
		| 'ZSAR'
		| 'ZSCR'
		| 'ZSMC'
		| 'ZTCF'
		| 'ZTCR'
		| (string & {})
	logLnInst?: string
	logName?: string
	logPrefix?: string
	reasonCode?: string
}

export type AttributesLogParametersRef = {
	desc?: string
	id: string
}

export type AttributesLogSettings = {
	cbName?: 'Conf' | 'Fix' | (string & {})
	datSet?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
	intgPd?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
	logEna?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
	trgOps?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
}

export type AttributesMaxTime = {
	multiplier?:
		| ''
		| 'm'
		| 'k'
		| 'M'
		| 'mu'
		| 'y'
		| 'z'
		| 'a'
		| 'f'
		| 'p'
		| 'n'
		| 'c'
		| 'd'
		| 'da'
		| 'h'
		| 'G'
		| 'T'
		| 'P'
		| 'E'
		| 'Z'
		| 'Y'
		| (string & {})
	unit?: 's'
}

export type AttributesMcSecurity = {
	encryption?: string
	signature?: string
}

export type AttributesMinRequestedSCDFile = {
	desc?: string
	fileName?: string
	fileType: 'SCD' | 'ICD' | 'IID' | 'CID' | 'SSD' | 'SED' | (string & {})
	fileUuid?: string
	revision: string
	version: string
	when?: string
}

export type AttributesMinRequestedSCDFiles = {}

export type AttributesMinTime = {
	multiplier?:
		| ''
		| 'm'
		| 'k'
		| 'M'
		| 'mu'
		| 'y'
		| 'z'
		| 'a'
		| 'f'
		| 'p'
		| 'n'
		| 'c'
		| 'd'
		| 'da'
		| 'h'
		| 'G'
		| 'T'
		| 'P'
		| 'E'
		| 'Z'
		| 'Y'
		| (string & {})
	unit?: 's'
}

export type AttributesMultiAPPerSubNet = {}

export type AttributesNeutralPoint = {
	bayName?: string
	cNodeName: string
	cNodeUuid?: string
	connectivityNode: string
	desc?: string
	lineName?: string
	name?: string
	processName?: string
	substationName?: string
	voltageLevelName?: string
}

export type AttributesOptFields = {
	bufOvfl?: string
	configRef?: string
	dataRef?: string
	dataSet?: string
	entryID?: string
	reasonCode?: string
	seqNum?: string
	timeStamp?: string
}

export type AttributesOutputVar = {
	daName?: string
	dataName?: string
	desc?: string
	doName?: string
	lnodeUuid?: string
	outputName?: string
	outputUuid?: string
	value?: string
	varName: string
}

export type AttributesOutputVarRef = {
	desc?: string
	value?: string
	variable?: string
}

export type AttributesOutputs = {
	desc?: string
}

export type AttributesP = {
	type:
		| 'IP'
		| 'IP-SUBNET'
		| 'IP-GATEWAY'
		| 'OSI-NSAP'
		| 'OSI-TSEL'
		| 'OSI-SSEL'
		| 'OSI-PSEL'
		| 'OSI-AP-Title'
		| 'OSI-AP-Invoke'
		| 'OSI-AE-Qualifier'
		| 'OSI-AE-Invoke'
		| 'MAC-Address'
		| 'APPID'
		| 'VLAN-PRIORITY'
		| 'VLAN-ID'
		| 'SNTP-Port'
		| 'MMS-Port'
		| 'DNSName'
		| 'IPv6FlowLabel'
		| 'IPv6ClassOfTraffic'
		| 'C37-118-IP-Port'
		| 'IP-UDP-PORT'
		| 'IP-TCP-PORT'
		| 'IPv6'
		| 'IPv6-SUBNET'
		| 'IPv6-GATEWAY'
		| 'IPv6-IGMPv3Src'
		| 'IP-IGMPv3Src'
		| 'IP-ClassOfTraffic'
		| (string & {})
}

export type AttributesPhysConn = {
	desc?: string
	type: 'Connection' | 'RedConn' | (string & {})
}

export type AttributesPowerSystemRelation = {
	desc?: string
	name: string
	originUuid?: string
	relation?: string
	relationUuid?: string
	selector?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesPowerSystemRelationRef = {
	desc?: string
	powerSystemRelation?: string
	powerSystemRelationUuid?: string
}

export type AttributesPowerSystemRelations = {
	desc?: string
}

export type AttributesPowerTransformer = {
	desc?: string
	name: string
	templateUuid?: string
	type: 'PTR' | (string & {})
	uuid?: string
	virtual?: string
}

export type AttributesPrivate = {
	source?: string
	type: string
}

export type AttributesProcess = {
	desc?: string
	name: string
	templateUuid?: string
	type?: string
	uuid?: string
}

export type AttributesProcessEcho = {
	desc?: string
	source?: string
	sourceDaName?: string
	sourceDoName?: string
	sourceLNodeUuid?: string
}

export type AttributesProcessResource = {
	cardinality?: '0..1' | '1..1' | '0..n' | '1..n' | (string & {})
	desc?: string
	max?: string
	name: string
	originUuid?: string
	selector?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesProcessResourceRef = {
	desc?: string
	processResource?: string
	processResourceUuid?: string
}

export type AttributesProcessResources = {
	desc?: string
}

export type AttributesProject = {
	desc?: string
	name: string
	uuid?: string
}

export type AttributesProjectProcessReference = {
	desc?: string
	processReference?: string
	processUuid?: string
}

export type AttributesProtNs = {
	type?: string
}

export type AttributesProtocol = {
	mustUnderstand: 'true'
}

export type AttributesReadWrite = {}

export type AttributesRedProt = {
	hsr?: string
	prp?: string
	rstp?: string
}

export type AttributesReportControl = {
	bufTime?: string
	buffered?: string
	confRev: string
	datSet?: string
	desc?: string
	indexed?: string
	intgPd?: string
	name: string
	rptID?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesReportParameters = {
	bufTime?: string
	buffered?: string
	cbName?: string
	desc?: string
	dsName?: string
	id: string
	intgPd?: string
}

export type AttributesReportParametersRef = {
	desc?: string
	id: string
}

export type AttributesReportSettings = {
	bufTime?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
	cbName?: 'Conf' | 'Fix' | (string & {})
	datSet?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
	intgPd?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
	optFields?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
	owner?: string
	resvTms?: string
	rptID?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
	trgOps?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
}

export type AttributesResource = {
	resInst?: string
	source?: string
	sourceUuid?: string
}

export type AttributesRptEnabled = {
	desc?: string
	max?: string
}

export type AttributesSCL = {
	release: '5'
	revision: 'C'
	version: '2007'
}

export type AttributesSCSM = {
	iec61850_8_1?: string
	iec61850_8_2?: string
	serverAssociationInitiation?: string
}

export type AttributesSDI = {
	desc?: string
	ix?: string
	name:
		| 'T'
		| 'Test'
		| 'Check'
		| 'SIUnit'
		| 'Oper'
		| 'SBO'
		| 'SBOw'
		| 'Cancel'
		| 'Addr'
		| 'PRIORITY'
		| 'VID'
		| 'APPID'
		| 'TransportInUse'
		| 'IPClassOfTraffic'
		| 'IPv6FlowLabel'
		| 'IPAddressLength'
		| 'IPAddress'
		| (string & {})
	sAddr?: string
}

export type AttributesSDO = {
	count?: string
	desc?: string
	name: string
	type: string
}

export type AttributesSDS = {
	desc?: string
	ix?: string
	mappedDoName?: string
	mappedLnUuid?: string
	name:
		| 'T'
		| 'Test'
		| 'Check'
		| 'SIUnit'
		| 'Oper'
		| 'SBO'
		| 'SBOw'
		| 'Cancel'
		| 'Addr'
		| 'PRIORITY'
		| 'VID'
		| 'APPID'
		| 'TransportInUse'
		| 'IPClassOfTraffic'
		| 'IPv6FlowLabel'
		| 'IPAddressLength'
		| 'IPAddress'
		| (string & {})
}

export type AttributesSGEdit = {
	resvTms?: string
}

export type AttributesSMV = {
	cbName: string
	cbUuid?: string
	desc?: string
	ldInst: string
}

export type AttributesSMVParameters = {
	cbName?: string
	desc?: string
	dsName?: string
	id: string
	multicast?: string
	nofASDU?: string
	securityEnabled?: string
	smpMod?: 'SmpPerPeriod' | 'SmpPerSec' | 'SecPerSmp' | (string & {})
	smpRate?: string
	smvId?: string
}

export type AttributesSMVParametersRef = {
	desc?: string
	id: string
}

export type AttributesSMVSecurity = {
	desc?: string
	name: string
	serialNumber: string
	templateUuid?: string
	uuid?: string
	xferNumber?: string
}

export type AttributesSMVSettings = {
	cbName?: 'Conf' | 'Fix' | (string & {})
	datSet?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
	kdaParticipant?: string
	nofASDU?: 'Conf' | 'Fix' | (string & {})
	optFields?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
	pdcTimeStamp?: string
	samplesPerSec?: string
	smpRate?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
	svID?: 'Dyn' | 'Conf' | 'Fix' | (string & {})
	synchSrcId?: string
}

export type AttributesSMVsc = {
	delivery?: 'unicast' | 'multicast' | 'both' | (string & {})
	deliveryConf?: string
	max: string
	rSV?: string
	sv?: string
}

export type AttributesSVMcSecurity = {
	encryption?: string
	signature?: string
}

export type AttributesSampledValueControl = {
	confRev?: string
	datSet?: string
	desc?: string
	multicast?: string
	name: string
	nofASDU: string
	securityEnable?: 'None' | 'Signature' | 'SignatureAndEncryption' | (string & {})
	smpMod?: 'SmpPerPeriod' | 'SmpPerSec' | 'SecPerSmp' | (string & {})
	smpRate: string
	smvID: string
	templateUuid?: string
	uuid?: string
}

export type AttributesSamplesPerSec = {}

export type AttributesSclFileReference = {
	desc?: string
	fileName?: string
	fileType: 'ICD' | 'IID' | 'CID' | 'SSD' | 'SCD' | 'SED' | (string & {})
	fileUuid?: string
	revision: string
	version: string
	when?: string
}

export type AttributesSecPerSamples = {}

export type AttributesSecurity = {
	ACSEAuthentication?: string
	E2ESecurity?: string
}

export type AttributesServer = {
	desc?: string
	timeout?: string
}

export type AttributesServerAt = {
	apName: string
	apUuid?: string
	desc?: string
}

export type AttributesServiceSpecifications = {
	desc?: string
}

export type AttributesServices = {
	nameLength?: string
}

export type AttributesSetDataSetValue = {}

export type AttributesSettingControl = {
	actSG?: string
	desc?: string
	numOfSGs: string
	resvTms?: string
}

export type AttributesSettingGroups = {}

export type AttributesSignalRole = {
	desc?: string
	name: string
	originUuid?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesSmpRate = {}

export type AttributesSmvOpts = {
	dataSet?: string
	refreshTime?: string
	sampleMode?: string
	sampleRate?: string
	sampleSynchronized?: 'true'
	security?: string
	synchSourceId?: string
	timestamp?: string
}

export type AttributesSourceFiles = {}

export type AttributesSourceRef = {
	desc?: string
	extRefAddr?: string
	extRefUuid?: string
	input: string
	inputInst?: string
	originUuid?: string
	pDA?: string
	pDO?: string
	pLN?: string
	resourceName?: string
	resourceUuid?: string
	service?: 'Poll' | 'Report' | 'GOOSE' | 'SMV' | 'Wired' | 'Internal' | (string & {})
	source?: string
	sourceDaName?: string
	sourceDoName?: string
	sourceLNodeUuid?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesSubCategory = {
	desc?: string
	name: string
	originUuid?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesSubCheckoutID = {
	desc?: string
	engRight?: 'full' | 'fix' | 'dataflow' | (string & {})
	fileName?: string
	fileType: 'SED' | 'SCC' | 'ICD' | 'IID' | 'CID' | 'SSD' | 'SCD' | (string & {})
	fileUuid?: string
	headerId?: string
	revision: string
	version: string
	when?: string
}

export type AttributesSubEquipment = {
	desc?: string
	name: string
	phase?: 'A' | 'B' | 'C' | 'N' | 'all' | 'none' | 'AB' | 'BC' | 'CA' | (string & {})
	templateUuid?: string
	uuid?: string
	virtual?: string
}

export type AttributesSubFunction = {
	desc?: string
	name: string
	templateUuid?: string
	type?: string
	uuid?: string
}

export type AttributesSubFunctionTemplate = {
	desc?: string
	name: string
	originUuid?: string
	templateUuid?: string
	type?: string
	uuid?: string
}

export type AttributesSubNetwork = {
	desc?: string
	name: string
	templateUuid?: string
	type?: '8-MMS' | '8-XMPP' | (string & {})
	uuid?: string
}

export type AttributesSubject = {
	commonName: string
	idHierarchy: string
}

export type AttributesSubscriberLNode = {
	desc?: string
	inputName: string
	pLN?: string
	resourceName?: string
	resourceUuid?: string
	service?: 'Poll' | 'Report' | 'GOOSE' | 'SMV' | 'Wired' | 'Internal' | (string & {})
}

export type AttributesSubstation = {
	desc?: string
	name: string
	templateUuid?: string
	uuid?: string
}

export type AttributesSupSubscription = {
	maxGo: string
	maxSv: string
}

export type AttributesTapChanger = {
	desc?: string
	name: string
	templateUuid?: string
	type: 'LTC'
	uuid?: string
	virtual?: string
}

export type AttributesTerminal = {
	bayName?: string
	cNodeName: string
	cNodeUuid?: string
	connectivityNode: string
	desc?: string
	lineName?: string
	name?: string
	processName?: string
	substationName?: string
	voltageLevelName?: string
}

export type AttributesText = {
	source?: string
}

export type AttributesTimeSyncProt = {
	c37_238?: string
	iec61850_9_3?: string
	other?: string
	sntp?: string
}

export type AttributesTimerActivatedControl = {}

export type AttributesTransformerWinding = {
	desc?: string
	name: string
	templateUuid?: string
	type: 'PTW' | (string & {})
	uuid?: string
	virtual?: string
}

export type AttributesTrgOps = {
	dchg?: string
	dupd?: string
	gi?: string
	period?: string
	qchg?: string
}

export type AttributesVal = {
	sGroup?: string
}

export type AttributesValueHandling = {
	setToRO?: string
}

export type AttributesVariable = {
	desc?: string
	name: string
	originUuid?: string
	templateUuid?: string
	uuid?: string
	value?: string
}

export type AttributesVariableApplyTo = {
	attribute?: string
	daName?: string
	defaultValue?: string
	desc?: string
	doName?: string
	element?: string
	elementUuid?: string
	format?: string
	sGroup?: string
}

export type AttributesVariableRef = {
	desc?: string
	value?: string
	variable?: string
	variableUuid?: string
}

export type AttributesVoltage = {
	multiplier?:
		| ''
		| 'm'
		| 'k'
		| 'M'
		| 'mu'
		| 'y'
		| 'z'
		| 'a'
		| 'f'
		| 'p'
		| 'n'
		| 'c'
		| 'd'
		| 'da'
		| 'h'
		| 'G'
		| 'T'
		| 'P'
		| 'E'
		| 'Z'
		| 'Y'
		| (string & {})
	unit: 'V'
}

export type AttributesVoltageLevel = {
	desc?: string
	name: string
	nomFreq?: string
	numPhases?: string
	templateUuid?: string
	uuid?: string
}

export type AttributesMap = {
	AccessControl: AttributesAccessControl
	AccessPoint: AttributesAccessPoint
	Address: AttributesAddress
	AllocationRole: AttributesAllocationRole
	AllocationRoleRef: AttributesAllocationRoleRef
	AnalogueWiringParameters: AttributesAnalogueWiringParameters
	AnalogueWiringParametersRef: AttributesAnalogueWiringParametersRef
	Application: AttributesApplication
	ApplicationSclRef: AttributesApplicationSclRef
	Association: AttributesAssociation
	Authentication: AttributesAuthentication
	BDA: AttributesBDA
	Bay: AttributesBay
	BayType: AttributesBayType
	BehaviorDescription: AttributesBehaviorDescription
	BehaviorDescriptionRef: AttributesBehaviorDescriptionRef
	BehaviorReference: AttributesBehaviorReference
	BinaryWiringParameters: AttributesBinaryWiringParameters
	BinaryWiringParametersRef: AttributesBinaryWiringParametersRef
	BitRate: AttributesBitRate
	CheckoutID: AttributesCheckoutID
	ClientLN: AttributesClientLN
	ClientServices: AttributesClientServices
	CommProt: AttributesCommProt
	Communication: AttributesCommunication
	CommunicationServiceSpecifications: AttributesCommunicationServiceSpecifications
	ConductingEquipment: AttributesConductingEquipment
	ConfDataSet: AttributesConfDataSet
	ConfLNs: AttributesConfLNs
	ConfLdName: AttributesConfLdName
	ConfLogControl: AttributesConfLogControl
	ConfReportControl: AttributesConfReportControl
	ConfSG: AttributesConfSG
	ConfSigRef: AttributesConfSigRef
	ConnectedAP: AttributesConnectedAP
	ConnectivityNode: AttributesConnectivityNode
	ControlRef: AttributesControlRef
	ControllingLNode: AttributesControllingLNode
	DA: AttributesDA
	DAI: AttributesDAI
	DAS: AttributesDAS
	DAType: AttributesDAType
	DO: AttributesDO
	DOI: AttributesDOI
	DOS: AttributesDOS
	DOType: AttributesDOType
	DataObjectDirectory: AttributesDataObjectDirectory
	DataSet: AttributesDataSet
	DataSetDirectory: AttributesDataSetDirectory
	DataTypeTemplates: AttributesDataTypeTemplates
	DynAssociation: AttributesDynAssociation
	DynDataSet: AttributesDynDataSet
	EnumType: AttributesEnumType
	EnumVal: AttributesEnumVal
	EqFunction: AttributesEqFunction
	EqSubFunction: AttributesEqSubFunction
	ExtCtrl: AttributesExtCtrl
	ExtRef: AttributesExtRef
	FCDA: AttributesFCDA
	FileHandling: AttributesFileHandling
	Function: AttributesFunction
	FunctionCatRef: AttributesFunctionCatRef
	FunctionCategory: AttributesFunctionCategory
	FunctionCategoryRef: AttributesFunctionCategoryRef
	FunctionRef: AttributesFunctionRef
	FunctionRole: AttributesFunctionRole
	FunctionRoleContent: AttributesFunctionRoleContent
	FunctionSclRef: AttributesFunctionSclRef
	FunctionTemplate: AttributesFunctionTemplate
	FunctionalSubVariant: AttributesFunctionalSubVariant
	FunctionalVariant: AttributesFunctionalVariant
	FunctionalVariantGroup: AttributesFunctionalVariantGroup
	FunctionalVariantRef: AttributesFunctionalVariantRef
	GOOSE: AttributesGOOSE
	GOOSEMcSecurity: AttributesGOOSEMcSecurity
	GOOSESecurity: AttributesGOOSESecurity
	GSE: AttributesGSE
	GSEControl: AttributesGSEControl
	GSEDir: AttributesGSEDir
	GSESettings: AttributesGSESettings
	GSSE: AttributesGSSE
	GeneralEquipment: AttributesGeneralEquipment
	GetCBValues: AttributesGetCBValues
	GetDataObjectDefinition: AttributesGetDataObjectDefinition
	GetDataSetValue: AttributesGetDataSetValue
	GetDirectory: AttributesGetDirectory
	GooseParameters: AttributesGooseParameters
	GooseParametersRef: AttributesGooseParametersRef
	Header: AttributesHeader
	History: AttributesHistory
	Hitem: AttributesHitem
	IED: AttributesIED
	IEDName: AttributesIEDName
	IEDSourceFiles: AttributesIEDSourceFiles
	InputVar: AttributesInputVar
	InputVarRef: AttributesInputVarRef
	Inputs: AttributesInputs
	IssuerName: AttributesIssuerName
	KDC: AttributesKDC
	L2CommParameters: AttributesL2CommParameters
	L3IPv4CommParameters: AttributesL3IPv4CommParameters
	L3IPv6CommParameters: AttributesL3IPv6CommParameters
	LDevice: AttributesLDevice
	LN: AttributesLN
	LN0: AttributesLN0
	LNode: AttributesLNode
	LNodeDataRef: AttributesLNodeDataRef
	LNodeInputRef: AttributesLNodeInputRef
	LNodeInputs: AttributesLNodeInputs
	LNodeOutputRef: AttributesLNodeOutputRef
	LNodeOutputs: AttributesLNodeOutputs
	LNodeSpecNaming: AttributesLNodeSpecNaming
	LNodeType: AttributesLNodeType
	Label: AttributesLabel
	Labels: AttributesLabels
	Line: AttributesLine
	Log: AttributesLog
	LogControl: AttributesLogControl
	LogParameters: AttributesLogParameters
	LogParametersRef: AttributesLogParametersRef
	LogSettings: AttributesLogSettings
	MaxTime: AttributesMaxTime
	McSecurity: AttributesMcSecurity
	MinRequestedSCDFile: AttributesMinRequestedSCDFile
	MinRequestedSCDFiles: AttributesMinRequestedSCDFiles
	MinTime: AttributesMinTime
	MultiAPPerSubNet: AttributesMultiAPPerSubNet
	NeutralPoint: AttributesNeutralPoint
	OptFields: AttributesOptFields
	OutputVar: AttributesOutputVar
	OutputVarRef: AttributesOutputVarRef
	Outputs: AttributesOutputs
	P: AttributesP
	PhysConn: AttributesPhysConn
	PowerSystemRelation: AttributesPowerSystemRelation
	PowerSystemRelationRef: AttributesPowerSystemRelationRef
	PowerSystemRelations: AttributesPowerSystemRelations
	PowerTransformer: AttributesPowerTransformer
	Private: AttributesPrivate
	Process: AttributesProcess
	ProcessEcho: AttributesProcessEcho
	ProcessResource: AttributesProcessResource
	ProcessResourceRef: AttributesProcessResourceRef
	ProcessResources: AttributesProcessResources
	Project: AttributesProject
	ProjectProcessReference: AttributesProjectProcessReference
	ProtNs: AttributesProtNs
	Protocol: AttributesProtocol
	ReadWrite: AttributesReadWrite
	RedProt: AttributesRedProt
	ReportControl: AttributesReportControl
	ReportParameters: AttributesReportParameters
	ReportParametersRef: AttributesReportParametersRef
	ReportSettings: AttributesReportSettings
	Resource: AttributesResource
	RptEnabled: AttributesRptEnabled
	SCL: AttributesSCL
	SCSM: AttributesSCSM
	SDI: AttributesSDI
	SDO: AttributesSDO
	SDS: AttributesSDS
	SGEdit: AttributesSGEdit
	SMV: AttributesSMV
	SMVParameters: AttributesSMVParameters
	SMVParametersRef: AttributesSMVParametersRef
	SMVSecurity: AttributesSMVSecurity
	SMVSettings: AttributesSMVSettings
	SMVsc: AttributesSMVsc
	SVMcSecurity: AttributesSVMcSecurity
	SampledValueControl: AttributesSampledValueControl
	SamplesPerSec: AttributesSamplesPerSec
	SclFileReference: AttributesSclFileReference
	SecPerSamples: AttributesSecPerSamples
	Security: AttributesSecurity
	Server: AttributesServer
	ServerAt: AttributesServerAt
	ServiceSpecifications: AttributesServiceSpecifications
	Services: AttributesServices
	SetDataSetValue: AttributesSetDataSetValue
	SettingControl: AttributesSettingControl
	SettingGroups: AttributesSettingGroups
	SignalRole: AttributesSignalRole
	SmpRate: AttributesSmpRate
	SmvOpts: AttributesSmvOpts
	SourceFiles: AttributesSourceFiles
	SourceRef: AttributesSourceRef
	SubCategory: AttributesSubCategory
	SubCheckoutID: AttributesSubCheckoutID
	SubEquipment: AttributesSubEquipment
	SubFunction: AttributesSubFunction
	SubFunctionTemplate: AttributesSubFunctionTemplate
	SubNetwork: AttributesSubNetwork
	Subject: AttributesSubject
	SubscriberLNode: AttributesSubscriberLNode
	Substation: AttributesSubstation
	SupSubscription: AttributesSupSubscription
	TapChanger: AttributesTapChanger
	Terminal: AttributesTerminal
	Text: AttributesText
	TimeSyncProt: AttributesTimeSyncProt
	TimerActivatedControl: AttributesTimerActivatedControl
	TransformerWinding: AttributesTransformerWinding
	TrgOps: AttributesTrgOps
	Val: AttributesVal
	ValueHandling: AttributesValueHandling
	Variable: AttributesVariable
	VariableApplyTo: AttributesVariableApplyTo
	VariableRef: AttributesVariableRef
	Voltage: AttributesVoltage
	VoltageLevel: AttributesVoltageLevel
}

export type AttributesOf<T extends AvailableElement> = AttributesMap[T]

export type RequiredAttributeNames<T extends AvailableElement> =
	(typeof REQUIRED_ATTRIBUTES)[T][number]
export type OptionalAttributeNames<T extends AvailableElement> = Exclude<
	keyof AttributesOf<T>,
	RequiredAttributeNames<T>
>
